### ISSUE TITLE
Add scrolling-padding-top: 100px; to docs template

### ISSUE THREAD

**Issue by particthistle** [joomla/docs.joomla.org#3]
@conconnl as per the PR's from last October:
https://github.com/joomla/joomla-websites/issues/1546
https://github.com/joomla/jdotorgtemplate/issues/181

It looks like the addition of scroll-padding-top that was added to the main templates has not made it across to the jdocs template.

```
  html { 
    scroll-padding-top: 100px; /* height of sticky header on Joomla template */ 
  }
```
Can you added it to resolve the issue raised today in JDocs Working Group on Glip with the jumping to an anchor on the page tucking underneath the sticky header.

**Comment by conconnl** [comment]
I think most of the website do not even have the latest template.
JDoc is not Joomla, the template is not even in this repository.
I have no clue how the docs system works, the site maintainer still needs to build the repository and do other things, before anybody can provide PRs and such things.

The only thing I know it's located somewhere outside of Joomla.
See: https://github.com/joomla/docs.joomla.org/issues/2

**Comment by Harsh-Porwal424** [comment]
Hello Patrick Jackson I want to work on this issue.
Please assign this issue to me

**Comment by conconnl** [comment]
@wilsonge can you add the right files in the repository so we can update the template parts via a PR?

**Comment by particthistle** [comment]
@mysteriouspla issues like these are part of Joomla's website management, so aren't issues you can work on. If you're looking at participating in contributing more to Joomla get in touch.

@wilsonge any chance of getting to this so that the UX on the docs template is improved?

**Comment by particthistle** [comment]
@wilsonge could you add this request to https://github.com/Hutchy68/Jforeground/pull/6 so that it's ready for inclusion when WikiMedia get updated.

**Comment by karan-vaishnav** [comment]
Hello Sir,
may I work on this issue??

**Comment by particthistle** [comment]
@karan-vaishnav nothing to work on here - this is an issue that @wilsonge needs to address by just adding the appropriate line of CSS to the template.

**Comment by utkarsh-shrivastav77** [comment]
sir I want to Contribute can you guide me

**Comment by particthistle** [comment]
> sir I want to Contribute can you guide me

This is not an issue to contribute to @utkarsh-shrivastav77 

[Start here to find out more about ways you can contribute to Joomla.](https://www.joomla.org/contribute-to-joomla.html)

**Comment by HLeithner** [comment]
I'm closing this because we will reuse this repository for the upcoming joomla next documentation.
