### ISSUE TITLE
Navbar is Not working Properly

### ISSUE THREAD

**Issue by skpandey885** [joomla/docs.joomla.org#5]
**CURRENT BEHAVIOUR:** When you go to https://docs.joomla.org from any Mobile device. The Navbar Keeps floating when you scroll down.
 
<img width="466" alt="Screenshot 2022-03-20 at 12 47 06 AM" src="https://user-images.githubusercontent.com/78532081/159135342-95444461-0ce2-4332-b22e-fbcfbabc3bba.png">

**Comment by skpandey885** [comment]
@maintainers Please assign me this issue. So that I can work on it.

**Comment by utkarsh-shrivastav77** [comment]
can you assign me this issue.so that I can work on it

**Comment by avanishkhursange** [comment]
Assign me this issue . So i can work on it

**Comment by HLeithner** [comment]
Can't replicate the issue, which browser is it? maybe it's already fixed in the meantime. I'm closing this for now. If you have further information you can reopen the issue
