### ISSUE TITLE
Anomaly in Chunk4x Title render

### ISSUE THREAD

**Issue by ceford** [joomla/docs.joomla.org#6]
Compare these three URLs:

https://docs.joomla.org/Chunk4x:Extensions_Plugin_Manager_Edit_Action_Log_Group
https://docs.joomla.org/Chunk4x:Extensions_Plugin_Manager_Edit_Action_Log_Group/en
https://docs.joomla.org/Chunk4x:Extensions_Plugin_Manager_Edit_Action_Log_Group/de

The article titles all have the Chunk4x namespace and look like this:

Extensions Plugin Manager Edit Action Log Group
Chunk4x:Extensions Plugin Manager Edit Action Log Group
Erweiterungen Plugin Manager Aktionsprotokollgruppe bearbeiten

So the automated /en translation is having Chunk4x carried through into the title. That is a problem because in some places the Chunks are used as stand-alone documents.

**Comment by Ayush-Kori** [comment]
Hey @ceford I am going to work on this issue.

**Comment by anayatkhan1** [comment]
Hello @ceford 👋, i would like work on this issue, can you assign me.

**Comment by ceford** [comment]
I have no powers to do anything here. As far as I know you just work on the problem and create a pull request for the site administrator to merge or not as he sees fit.

**Comment by max123kl** [comment]
There are other pages affected by this issue:
https://docs.joomla.org/Help4.x:Extensions:_Manage
https://docs.joomla.org/Help4.x:Extensions:_Manage/en
https://docs.joomla.org/Help4.x:Extensions:_Manage/de

https://docs.joomla.org/Help4.x:Users:_Edit_Profile
https://docs.joomla.org/Help4.x:Users:_Edit_Profile/en
https://docs.joomla.org/Help4.x:Users:_Edit_Profile/nl

https://docs.joomla.org/Help4.x:Articles:_Edit
https://docs.joomla.org/Help4.x:Articles:_Edit/en
https://docs.joomla.org/Help4.x:Articles:_Edit/de

and many others

**Comment by HLeithner** [comment]
I'm closing this because we will reuse this repository for the upcoming joomla next documentation.
